### PR TITLE
[ENH] Add warning block and puts warning in a collapsable detail element

### LINKED ISSUE #23: Put warnings in a jinja block
Tempted to use this template for a project that I maintain.

We a LOT of warnings when running our test suite so I'd like to be able to collapse the warning section in a details HTML element.

Unless I am mistaken at the moment I have to pretty much use the whole template and tweak it because I cannot just inherit and tweak the warning section because it is not in a jinja block.

Do you think it would be OK to add a block for the warning section to make the template more modular?

### PR DESCRIPTION
**Pull request by Remi-Gau**
- closes #23 

---

- add a test that throws warnings
- add a jinja black for warnings
- put warnings into a detail element

### CODE REVIEW

**Comment by Remi-Gau** [comment]
Sending snapshots eventhough the workflow seems to upload testing artefacts for quick inspection.

image

image

**Comment by Remi-Gau** [comment]
I know the styling needs more work: let me know what you would prefer and I can try to make it work.

I have started adding more styling things in a the downstream template that I use, but I am not sure it makes sense to put them in this PR.

For my usecase it makes sense to sort warnings by category first and then by file where they occur but maybe other people will want something different.

So let me know what you think would be a good default for the package.

**Comment by christiansandberg** [comment]
I think you need to update the CSS to reflect the extra level so that the badge and text aligns correctly.

**Comment by Remi-Gau** [comment]
Made some adjustments that should be fine in most use case (I hope)

image

image

**Pull request merged**
